# Generated by Django 4.2.2 on 2023-07-26 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('biography', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('deleted_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateField(null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishLists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wishlist_name', models.CharField(default='0', max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.users')),
            ],
        ),
        migrations.CreateModel(
            name='WishListBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
                ('wish_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.wishlists')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCarts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.users')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCartBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('deleted_at', models.DateField(null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
                ('shopping_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.shoppingcarts')),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiration_date', models.DateField(blank=True, max_length=16, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='djangoBookStoreApi.users')),
            ],
        ),
        migrations.CreateModel(
            name='BookRatings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.SmallIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.users')),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('copies_sold', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
            ],
        ),
        migrations.CreateModel(
            name='BookComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoBookStoreApi.users')),
            ],
        ),
    ]
