# Generated by Django 4.2.1 on 2023-07-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='genre',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
