# Generated by Django 4.2.1 on 2023-07-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0002_bookdetails_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookdetails',
            name='copies_sold',
        ),
        migrations.AddField(
            model_name='books',
            name='genre',
            field=models.CharField(default='Unkown', max_length=255),
            preserve_default=False,
        ),
    ]
