# Generated by Django 4.2.2 on 2023-07-21 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0005_alter_wishlists_wishlist_name'),
        ('djangoBookStoreApi', '0025_bookratings'),
    ]

    operations = [
    ]
