# Generated by Django 3.2.12 on 2023-07-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoBookStoreApi', '0005_alter_wishlists_wishlist_name'),
        ('djangoBookStoreApi', '0025_bookratings'),
    ]

    operations = [
    ]
